spring:
  profiles:
    include: oauth

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb

  session:
    store-type: jdbc
